directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: com.pedifacil.admin
asar: true
productName: Admin pedifacil
files:
  - filter:
      - dist
      - dist-electron
      - public/logo.png
extraResources:
  - from: public/logo.png
    to: logo.png
mac:
  target:
    - dmg
  icon: public/logo.png
  artifactName: ${productName}-Mac-${version}-Installer.${ext}
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/logo.png
  artifactName: ${productName}-Windows-${version}-Setup.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
linux:
  target:
    - AppImage
  icon: public/logo.png
  artifactName: ${productName}-Linux-${version}.${ext}
electronVersion: 30.5.1
